# try:
#     print(x)
# except:
#     print("An exception occurred")
#######################################3

# try:
#     print(x) # NameError
#     print(int('ali')) # another error
# except NameError:
#     print("Variable x is not defined")
# except:
#     print("Something else went wrong")

#########################################
# try:
#     print("Hello")
#     # print(x)
# except:
#     print("Something went wrong")
# else:
#     print("Nothing went wrong")

########################################3
# try:
#     print("hello")
# except:
#     print("Something went wrong")
# finally:
#     print("The 'try except' is finished")